name: my_assist
description: Credit Card Transaction Tracker
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_database: ^11.1.0

  # SMS
#  telephony: ^0.2.0
#  telephony_sms_handler: ^0.2.1
  flutter_sms_inbox: ^1.0.3

  # State management
  provider: ^6.1.2

  # Storage
  shared_preferences: ^2.3.2

  # UI
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  lottie: ^3.1.2
  permission_handler: ^11.3.1

  # App Icon
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon_1024.png"
  min_sdk_android: 21
  adaptive_icon_background: "#6C63FF"
  adaptive_icon_foreground: "assets/icon_1024.png"